module.exports = [
  {
    name: "Echoes of the Void",
    description:
      "A team of explorers uncovers secrets beneath the surface of a dying planet.",
    duration: 127,
    rating: 4.2,
    totalRatings: 982,
    releaseYear: 2023,
    releaseDate: new Date("2023-07-11"),
    createdAt: new Date(),
    genres: ["Sci-Fi", "Mystery", "Drama"],
    image: "https://example.com/images/echoes-of-the-void.jpg",
    actors: ["Clara Jensen", "Noah Reed", "Victor Hale"],
    price: 12.99,
  },
  {
    name: "Steel Horizon",
    description:
      "In a war-torn future, a rogue pilot must protect the last flying city.",
    duration: 105,
    rating: 4.1,
    totalRatings: 1103,
    releaseYear: 2022,
    releaseDate: new Date("2022-10-03"),
    createdAt: new Date(),
    genres: ["Action", "Adventure", "Sci-Fi"],
    image: "https://example.com/images/steel-horizon.jpg",
    actors: ["Ethan Black", "Zara Moon", "Leo Carter"],
    price: 13.49,
  },
  {
    name: "Neon Ashes",
    description:
      "In a cyberpunk city, a hacker discovers a conspiracy that could change reality itself.",
    duration: 119,
    rating: 4.6,
    totalRatings: 2214,
    releaseYear: 2024,
    releaseDate: new Date("2024-02-18"),
    createdAt: new Date(),
    genres: ["Thriller", "Sci-Fi"],
    image: "https://example.com/images/neon-ashes.jpg",
    actors: ["Kai Morgan", "Rina Delgado", "Xander Knox"],
    price: 15.99,
  },
  {
    name: "Moonfall Protocol",
    description:
      "A malfunction on a lunar base triggers a chain of events threatening Earth.",
    duration: 132,
    rating: 4.3,
    totalRatings: 1741,
    releaseYear: 2021,
    releaseDate: new Date("2021-12-12"),
    createdAt: new Date(),
    genres: ["Sci-Fi", "Action"],
    image: "https://example.com/images/moonfall-protocol.jpg",
    actors: ["Elena Frost", "Troy Vance", "Maya Silva"],
    price: 14.49,
  },
  {
    name: "Shadow Pulse",
    description:
      "A secret agent is caught in a deadly mind-control experiment.",
    duration: 101,
    rating: 4.0,
    totalRatings: 834,
    releaseYear: 2020,
    releaseDate: new Date("2020-05-09"),
    createdAt: new Date(),
    genres: ["Action", "Thriller"],
    image: "https://example.com/images/shadow-pulse.jpg",
    actors: ["Jaxon Steele", "Naomi Pierce", "Zane Beckett"],
    price: 11.99,
  },
  {
    name: "Solar Divide",
    description:
      "Earth’s future hinges on a risky solar mission by an untested crew.",
    duration: 124,
    rating: 4.7,
    totalRatings: 2645,
    releaseYear: 2023,
    releaseDate: new Date("2023-08-25"),
    createdAt: new Date(),
    genres: ["Drama", "Sci-Fi"],
    image: "https://example.com/images/solar-divide.jpg",
    actors: ["Aria Stone", "Luca Hayes", "Marin Wolf"],
    price: 13.75,
  },
  {
    name: "Mirage Protocol",
    description:
      "In a desert city plagued by illusions, a detective uncovers the truth.",
    duration: 108,
    rating: 3.9,
    totalRatings: 789,
    releaseYear: 2019,
    releaseDate: new Date("2019-03-13"),
    createdAt: new Date(),
    genres: ["Mystery", "Thriller"],
    image: "https://example.com/images/mirage-protocol.jpg",
    actors: ["Jude Falcon", "Sera Lin", "Derek Wells"],
    price: 10.99,
  },
  {
    name: "Quantum Drift",
    description:
      "Two parallel timelines collide when a physicist’s invention goes wrong.",
    duration: 117,
    rating: 4.4,
    totalRatings: 1401,
    releaseYear: 2022,
    releaseDate: new Date("2022-04-21"),
    createdAt: new Date(),
    genres: ["Sci-Fi", "Thriller"],
    image: "https://example.com/images/quantum-drift.jpg",
    actors: ["Emily Hart", "Logan Pierce", "Kane Alvarez"],
    price: 14.25,
  },
  {
    name: "The Last Circuit",
    description:
      "A rogue AI threatens humanity after escaping a lab’s firewall.",
    duration: 110,
    rating: 4.2,
    totalRatings: 1042,
    releaseYear: 2021,
    releaseDate: new Date("2021-06-30"),
    createdAt: new Date(),
    genres: ["Sci-Fi", "Action"],
    image: "https://example.com/images/last-circuit.jpg",
    actors: ["Max Ryder", "Isla Cheng", "Felix Hunter"],
    price: 13.99,
  },
  {
    name: "Chrono War",
    description: "Time-traveling soldiers fight to protect a single timeline.",
    duration: 130,
    rating: 4.6,
    totalRatings: 1923,
    releaseYear: 2020,
    releaseDate: new Date("2020-11-15"),
    createdAt: new Date(),
    genres: ["Action", "Sci-Fi"],
    image: "https://example.com/images/chrono-war.jpg",
    actors: ["Leo Ardent", "Nova Daniels", "Briggs Carter"],
    price: 15.5,
  },
  {
    name: "Cyber Eden",
    description: "A digital utopia hides a dangerous secret.",
    duration: 109,
    rating: 4.0,
    totalRatings: 925,
    releaseYear: 2024,
    releaseDate: new Date("2024-01-28"),
    createdAt: new Date(),
    genres: ["Sci-Fi", "Mystery"],
    image: "https://example.com/images/cyber-eden.jpg",
    actors: ["Sienna Ray", "Kade Foster", "Juno Fox"],
    price: 13.0,
  },
  {
    name: "Phoenix Down",
    description:
      "After a catastrophic event, a survivor becomes the hope of humanity.",
    duration: 123,
    rating: 4.3,
    totalRatings: 1687,
    releaseYear: 2023,
    releaseDate: new Date("2023-09-10"),
    createdAt: new Date(),
    genres: ["Drama", "Action"],
    image: "https://example.com/images/phoenix-down.jpg",
    actors: ["Reed Walker", "Isis Vela", "Cole Mercer"],
    price: 14.25,
  },
  {
    name: "Zero Line",
    description: "A rogue physicist breaks all rules to reset the timeline.",
    duration: 111,
    rating: 4.1,
    totalRatings: 1123,
    releaseYear: 2021,
    releaseDate: new Date("2021-07-22"),
    createdAt: new Date(),
    genres: ["Thriller", "Sci-Fi"],
    image: "https://example.com/images/zero-line.jpg",
    actors: ["Dara Quinn", "Milo Crane", "Lana Black"],
    price: 12.75,
  },
  {
    name: "Beyond Orion",
    description:
      "A lone explorer makes first contact with a hidden alien civilization.",
    duration: 134,
    rating: 4.5,
    totalRatings: 2014,
    releaseYear: 2022,
    releaseDate: new Date("2022-06-01"),
    createdAt: new Date(),
    genres: ["Adventure", "Sci-Fi"],
    image: "https://example.com/images/beyond-orion.jpg",
    actors: ["Eva Stone", "Rhys Monroe", "Talon West"],
    price: 15.75,
  },
  {
    name: "The Drift Code",
    description:
      "A cyber-criminal must decode his own mind to escape a digital prison.",
    duration: 118,
    rating: 4.2,
    totalRatings: 1334,
    releaseYear: 2020,
    releaseDate: new Date("2020-03-19"),
    createdAt: new Date(),
    genres: ["Sci-Fi", "Thriller"],
    image: "https://example.com/images/drift-code.jpg",
    actors: ["Noel Sparks", "Avery Cole", "Jett Monroe"],
    price: 13.3,
  },
  {
    name: "Event Loop",
    description:
      "A developer stuck in an infinite loop must find the bug to escape reality.",
    duration: 96,
    rating: 3.8,
    totalRatings: 754,
    releaseYear: 2019,
    releaseDate: new Date("2019-08-30"),
    createdAt: new Date(),
    genres: ["Comedy", "Sci-Fi"],
    image: "https://example.com/images/event-loop.jpg",
    actors: ["Sam Codey", "Lila Syntax", "Dex Kernel"],
    price: 9.99,
  },
  {
    name: "Timecore",
    description:
      "A secret organization monitors time-travel anomalies worldwide.",
    duration: 121,
    rating: 4.4,
    totalRatings: 1892,
    releaseYear: 2024,
    releaseDate: new Date("2024-05-17"),
    createdAt: new Date(),
    genres: ["Sci-Fi", "Action"],
    image: "https://example.com/images/timecore.jpg",
    actors: ["Axel Byrne", "Sasha Lane", "Nico Volt"],
    price: 14.95,
  },
  {
    name: "Dark Vector",
    description: "An elite cyber task force must neutralize a rogue AI.",
    duration: 115,
    rating: 4.1,
    totalRatings: 1423,
    releaseYear: 2022,
    releaseDate: new Date("2022-02-14"),
    createdAt: new Date(),
    genres: ["Action", "Sci-Fi"],
    image: "https://example.com/images/dark-vector.jpg",
    actors: ["Victor Trace", "Lena Volt", "Roy Blaze"],
    price: 13.2,
  },
  {
    name: "Starlight Paradox",
    description:
      "A space traveler must choose between two timelines to save her crew.",
    duration: 129,
    rating: 4.6,
    totalRatings: 1978,
    releaseYear: 2023,
    releaseDate: new Date("2023-11-02"),
    createdAt: new Date(),
    genres: ["Sci-Fi", "Drama"],
    image: "https://example.com/images/starlight-paradox.jpg",
    actors: ["Celeste Nova", "Ray Cosmo", "Drake Hale"],
    price: 15.6,
  },
];
